server:
  port: 8761
eureka:
  datacenter: trmap
  environment: product
  server:
      # 关闭自我保护
      enable-self-preservation: false
      # 清理服务器
      eviction-interval-timer-in-ms: 5000
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false