server:
  port: 8800
spring:
  application:
    name: sc-config-server
  cloud:
    config:
      server:
        git:
         uri: https://gitee.com/Migong/cloud-config.git
         username: *
         password: *
         searchPaths: '{application}'
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: sc-config-server
